#!/bin/sh

if [ $# -eq 1 ] ; then
	saffile=$1
else
	saffile="test_saf.saf"
fi
 
LINES=25
platform=`uname`
if [ "$platform" = "SunOS" ] ; then
	LINES=`stty -a | grep -i rows | sed 's/;//g' | grep -i rows | awk '{ print $3 }'`
fi
if [ "$platform" = "Linux" ] ; then
	LINES=`stty size | awk '{ print $1 }'`
fi

export LINES

	python -i safsh.py 


