#!/bin/sh

# Author: Robb Matzke <matzke@llnl.gov>
#
# Purpose:
#     Perform SAF Tier-I testing on local platform.
#
# Usage: tier1 [SAF_SOURCE_DIRECTORY [CONFIGURE_SWITCHES]]
#
#     This script takes one optional argument which is the name of the root of the SAF source tree.
#     If this argument is missing (or an empty string) then the script assumes that it lives in
#     the source tree.  Remaining arguments will be passed to `configure'.
# 
#     By default, the build will occur in /tmp/$USER. You can specify something different with
#     the `builddir' environment variable. All building will be done in `build/saf/.....'. These
#     directories will be removed first if they exist.
#
# Exit status:
#     If the configure, build, or test step fails for any configuration then this script immediately
#     exits with a non-zero status.
#
# Copyright(C) 1999 The Regents of the University of California.
#     This work  was produced, in  part, at the  University of California, Lawrence Livermore National
#     Laboratory    (UC LLNL)  under    contract number   W-7405-ENG-48 (Contract    48)   between the
#     U.S. Department of Energy (DOE) and The Regents of the University of California (University) for
#     the  operation of UC LLNL.  Copyright  is reserved to  the University for purposes of controlled
#     dissemination, commercialization  through formal licensing, or other  disposition under terms of
#     Contract 48; DOE policies, regulations and orders; and U.S. statutes.  The rights of the Federal
#     Government  are reserved under  Contract 48 subject  to the restrictions agreed  upon by DOE and
#     University.
# 
# Copyright(C) 1999 Sandia Corporation.
#     Under terms of Contract DE-AC04-94AL85000, there is a non-exclusive license for use of this work
#     on behalf of the U.S. Government.  Export  of this program may require a license from the United
#     States Government.
# 
# Disclaimer:
#     This document was  prepared as an account of  work sponsored by an agency  of  the United States
#     Government. Neither the United States  Government nor the United States Department of Energy nor 
#     the  University  of  California  nor  Sandia  Corporation nor any  of their employees  makes any 
#     warranty, expressed  or  implied, or  assumes   any  legal liability  or responsibility  for the 
#     accuracy,  completeness,  or  usefulness  of  any  information, apparatus,  product,  or process 
#     disclosed,  or  represents that its  use would   not infringe  privately owned rights. Reference 
#     herein  to any  specific commercial  product,  process,  or  service by  trade  name, trademark, 
#     manufacturer,  or  otherwise,  does  not   necessarily  constitute  or  imply  its  endorsement, 
#     recommendation, or favoring by the  United States Government   or the University of  California.  
#     The views and opinions of authors expressed herein do not necessarily state  or reflect those of
#     the  United  States Government or  the   University of California   and shall  not be  used  for
#     advertising or product endorsement purposes.
# 
# Acknowledgements:
#     Robb P. Matzke              LLNL - Author of various tools
#     Mark C. Miller              LLNL - Alpha/Beta user; minor debugging/enhancements 
#     Matthew J. O'Brien          LLNL - Author of various tools
#     James F. Reus               LLNL - Alpha/Beta user



# Where are we?
ARCH=`uname`
mydir="$0"
[ `echo $mydir |cut -c1` = '/' ] || mydir=`pwd`/$mydir
mydir=`echo $mydir |sed s@/tools/tier1@@`

# The first argument should be the name of the source directory. But if nothing, use the path
# of this script.  Convert to an absolute name and check its existence.
srcdir=$mydir
if [ -n "$1" ]; then
    srcdir="$1"
    shift
fi
[ `echo $srcdir |cut -c1` = '/' ] || srcdir=`pwd`/$srcdir
if [ ! -d "$srcdir/." ]; then
    echo "$0: cannot find source directory" >&2
    exit 1
fi

# Create a directory where we can build this stuff.
builddir=${builddir-/tmp/$USER}
mkdir -p $builddir || exit 1
home=`pwd`
cd $builddir || exit 1

# Where is configure?  Handle SAF or HDF5
config=$srcdir/src/configure
[ -f $config ] || config=$srcdir/configure
if [ ! -f $config ]; then
    echo "cannot find configure script under $srcdir or $srcdir/src" >&2
    exit 1
fi

# We use the `build_saf' script, which chooses compilers, compiler switches, etc. based on
# certain environment variables we give to it.  This script should be in the same location
# as this tier1 script.
build_saf=$mydir/tools/build_saf
[ -x $build_saf ] || build_saf=build_saf

# Environment variable that tells build_saf to remove the build directory before starting.
PRUNE=${PRUNE-y}; export PRUNE

# Print some last minute results...
echo "Tier1 settings:"
echo "  Location of source code:    srcdir = $srcdir"
echo "  GNU configure script:       config = $config"
echo "  SAF build script:        build_saf = $build_saf"
echo "  Build directory:          builddir = $builddir"

HDF5_DEFAULT=1.7.39
if [ -n "$HDF5" -a "$HDF5" != $HDF5_DEFAULT ]; then
    echo "  Non-standard HDF5:            HDF5 = $HDF5"
else
    HDF5=$HDF5_DEFAULT
fi
export HDF5

# Do the tests depending on the system. The official tier1 test is IRIX64
if [ "$ARCH" = IRIX64 ]; then
    COMPILER=mpich-1.2.5  CCMODE=64  PRODUCT=debug $build_saf $config "$@" || exit 1
    COMPILER=mpich-1.2.5  CCMODE=n32 PRODUCT=optim $build_saf $config "$@" || exit 1
    COMPILER=serial       CCMODE=64  PRODUCT=optim $build_saf $config "$@" || exit 1
    COMPILER=serial       CCMODE=n32 PRODUCT=debug $build_saf $config "$@" || exit 1
    echo "Successful Tier-1 test."
elif [ "$ARCH" = Linux ]; then
    echo "Faking a tier1 test (this isn't IRIX64)"
    COMPILER=mpich-1.2.5  CCMODE=64  PRODUCT=debug $build_saf $config "$@" || exit 1
    COMPILER=serial       CCMODE=64  PRODUCT=optim $build_saf $config "$@" || exit 1
    echo "Tests passed, although this isn't technically a Tier-1 platform."
else
    echo "Faking a tier1 test (this isn't IRIX64)"
    COMPILER=mpich-1.2.5             PRODUCT=debug $build_saf $config "$@" || exit 1
    COMPILER=serial                  PRODUCT=optim $build_saf $config "$@" || exit 1
    echo "Tests passed, although this isn't technically a Tier-1 platform."
fi

cd $home
rm -fr $builddir

exit 0
