/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saf_0005finit */


#ifndef _Included_saf_0005finit
#define _Included_saf_0005finit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     saf_0005finit
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_saf_1init_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     saf_0005finit
 * Method:    native_fin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_saf_1init_native_1fin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
